### ISSUE TITLE
Simplification for Websites that only use technically necessary cookies

### ISSUE THREAD

**Issue by RoyalPulp** [xini/silverstripe-cookie-consent#12]
Would be nice to have an option to simplify the output /popup for simple websites without thirdparty and other non-necessary cookies
Same box with text, but only one or two buttons : Akknowledge, (optional) Link to Cookie-Page
Thanks for looking into this
Hendrik

**Comment by xini** [comment]
Great idea! I'll have a look into this when I have time. Happy to accept PRs in the meantime.

**Comment by digitweaks** [comment]
Hi Xini, 

I would like to come back on this issue, as it's affecting anyone in the EU zone that doesn't use Marketing cookies but already have the entire system installed and fully tweaked. As no PR has been proposed, and no modification has been done on your side, could we consider this problem not solved? 

I'm not savvy at all when it comes to Git things otherwise I would have already made a PR. Now to be honest, I'm facing a deadline and that's the only issue left to solve. What makes me write all this is that the problem has been reported, and it has been reported more than a year ago. If that's not solved, let's not push this under the rug and keep this ticket opened until it's finally fixed once and for all.

Thanks for your understanding!

**Comment by xini** [comment]
@digitweaks, watch your tone and check your facts.

This issue has not been 'just closed'. I was closed as completed in commit https://github.com/xini/silverstripe-cookie-consent/commit/4a452b84e0bb52c661838b91420fed8b37540190, in version 3.4.0. 

You can see an example of this working here: https://www.erodental.org/

**Comment by digitweaks** [comment]
Here is the solution:

Line 93 of CookieConsent

public static function check($group = CookieConsent::NECESSARY)
    {
        $cookies = self::config()->get('cookies');
        if (!isset($cookies[$group])) {
            // Skip throwing the exception and just return false or handle differently
            return false;
        }

        $consent = self::getConsent();
        return array_search($group, $consent) !== false;
    }


That's it...

Me, I have to watch my tone? This is lazy work proven by facts, sorry but when we say we have problem, it's not to just click "Solved" and let people down. Do you know the time it takes for some newbies to retro-engineer other people's code?

I wouldn't be so mad right now if in the first place you had some empathy for people using your module, kindly asking some help that you don't provide. I found the solution myself thanks to chat GPT in 15 minutes, but that's after working intensively on my own implementations of many projects. So you should maybe revise the way you treat issues, instead of telling me to watch my mouth when I didn't insult you at all, I pointed out an evidence and a huge flaw in the module configuration.

And... the issue is not at all resolved technically as I installed the module today and I got the issue again, so maybe if you left a clue somewhere we wouldn't be here. 

I would have said Thank you, but your answer shows I have no reason to thank you on this matter.

**Comment by xini** [comment]
No. This issue was created to deal with the case where only necessary cookies are configured, to simplify the popup. That's solved. 

What you are referring to is when you don't configure any cookies at all, correct? If so, that would be a different issue? 

In what case do you have no cookies at all? You'd always have at least the PHP session cookie, as well as the cms-menu-sticky and cms-panel-collapsed cookies for admins, no?

**Comment by xini** [comment]
What does your cookie config look like? This is the default: 

```
Innoweb\CookieConsent\CookieConsent:
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
```

What does your code look like that uses `CookieConsent::check()`? What cookie category are you checking for?

**Comment by xini** [comment]
If you want me to solve this for you, I need to know what the issue is, so that I can reproduce it. 

What is your config, your usage and error message?

**Comment by digitweaks** [comment]
Sorry for this, I think we got lost in translation at some point. I take the blame for being unfiltered.

The issue is that unless we define Marketing cookies in the config, the module thrown an Emergency error stating that we have to define Marketing cookies. I made sure the group Marketing isn't there in the settings, reloaded the page and the error was thrown. So somewhere in the check of Groups, even if we don't need Marketing cookies, the check throws an error. Maybe it doesn't on Live mode, I didn't check that, but in Dev mode it does throw an error every time. 

So my config only has Necessary cookies, there's no other Group defined, but for some reason the Marketing group is necessary. I'm on a fresh installation through composer by the way.

The solution I found was to change this snippet which is on line 93 of CookieConsent class

public static function check($group = CookieConsent::NECESSARY)
{
    $cookies = self::config()->get('cookies');
    if (!isset($cookies[$group])) {
    // Skip throwing the exception and just return false or handle differently
    return false;
}

It returns false instead of throwning an Emergency error. From there we can delete the Marketing group created by default and even if I don't know if that's how I should solve this issue, it does the trick for me.

And my bad if you felt offended, next time I post on Github I'll remember that my tone can be misinterpreted, and I also know now how to check if a commit has been released (as I said, I'm not familiar with Github when it comes to these details). That said I think the issue was the same, that's why I commented on this thread. 

I didn't see any feedback so I assumed the issue got close unresolved. 
I know I tend to be very straight forward and my partners know me as such, but I can understand it can pass for being rude.

I'll come with some flowers and a pack of Belgian chocolate next time :)

**Comment by xini** [comment]
That is an understatement, yes.

And no, this is not the same issue.

I suspect that you check for 'Marketing' cookies somewhere in your templates? Can you search for the word 'Marketing' in all *.ss files in your project and see if it is used anywhere?

**Comment by digitweaks** [comment]
So I remove any mention of  <% if $CookieConsent(Marketing) %> and other  <% if $CookieConsent(Analytics) %> then it works without the error. So that means we can't use any conditional statement in the template unless the group is defined. It's not a big deal obviously as there's only one template to modify per project, I just like to have snippets I can reuse without additional tweaks.

**Comment by xini** [comment]
This is expected behavior. If you rely on / check for cookies in your code that haven't been defined, the module throws an error, because it means that some functionality won't work because the cookie group is not defined. 

But I see your point of wanting to reuse snippets the lazy way. I have created a new issue https://github.com/xini/silverstripe-cookie-consent/issues/19 and will change that behavior when I have time.
